
spring:
  application:
    name: server
  profiles:
    default: true
    active: default
  main:
    allow-bean-definition-overriding: true
info:
  component: Photo Sharing Application Server


server:
  port:
    8080

---
spring:
  cloud:
    config:
      uri: http://localhost:8080
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: photo_sharing
  datasource:
    url: "jdbc:postgresql://localhost:5433/photo_sharing_app"
    username: postgres
    password: 12345
  mail:
    host: smtp.gmail.com
    port: 465
    username: <<YOUR_EMAIL_ADDRESS>>
    password: <<YOUR_EMAIL_PASSWORD>>
    protocol: smtps
support:
  email: <<YOUR_EMAIL_ADDRESS>>